### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.job.IJobScheduler.cancel(int)' on a null object reference

### ISSUE THREAD

**Issue by visareshwar** [googlesamples/android-instant-apps#40]
Getting NPE in Andorid 7.0 (MI note 4)

12-20 15:08:45.689 17828-17828/? V/FA: Cancelling job. JobID: 1469022989
12-20 15:08:45.690 17828-17828/? D/AndroidRuntime: Shutting down VM
12-20 15:08:45.691 17828-17828/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.android.instant.analytics, PID: 17828
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.instant.analytics/com.example.android.instant.analytics.feature.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.job.IJobScheduler.cancel(int)' on a null object reference
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2696)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2757)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1504)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:163)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6237)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.job.IJobScheduler.cancel(int)' on a null object reference
                                                       at android.app.JobSchedulerImpl.cancel(JobSchedulerImpl.java:60)
                                                       at com.google.android.gms.internal.zzcki.zzbam(Unknown Source)
                                                       at com.google.android.gms.internal.zzcki.zzaxo(Unknown Source)
                                                       at com.google.android.gms.internal.zzcii.initialize(Unknown Source)
                                                       at com.google.android.gms.internal.zzchj.<init>(Unknown Source)
                                                       at com.google.android.gms.internal.zzchj.zzdu(Unknown Source)
                                                       at com.google.firebase.analytics.FirebaseAnalytics.getInstance(Unknown Source)
                                                       at com.example.android.instant.analytics.feature.MainActivity.onCreate(MainActivity.java:45)
                                                       at android.app.Activity.performCreate(Activity.java:6847)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2649)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2757) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1504) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:163) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6237) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by apik420** [comment]
762

**Comment by tuinui** [comment]
i face this issues the same. Any workaround?

**Comment by KevinLeigh** [comment]
I receive the same issue

**Comment by sharmag222cool** [comment]
Facing the same issue on Nougat devices only with play services version 11.4.0 and higher. Same code is working on Lollipop, Marshmallow and Oreo. Any Help?

**Comment by keyboardsurfer** [comment]
I can not reproduce this issue running on an emulator with API levels 24 - 27 with the given sample at this point. 
Can someone reconfirm that this issue (still) occurs with the given sample.

**Comment by visareshwar** [comment]
This if Fixed. Thanks
